[catalog.neovim-nvf]
name = "Neovim NVF"
category = "editor"

[templates.nvim]
input_path = "matugen-template.lua"
output_path = "$XDG_CONFIG_HOME/nvim/lua/matugen.lua"
post_hook = "bash '{{ config_dir }}/apply.sh'"
