color0 #4e4352
color1 #ffb4ab
color2 #e7b4ff
color3 #e4b6f9
color4 #ffb0cb
color5 #e7b4ff
color6 #e4b6f9
color7 #ebdfeb
color8 #9a8c9d
color9 #ffb4ab
color10 #e7b4ff
color11 #e4b6f9
color12 #ffb0cb
color13 #e7b4ff
color14 #e4b6f9
color15 #ebdfeb

cursor                #ebdfeb
cursor_text_color     #171119
background            #171119
foreground            #ebdfeb
selection_foreground  #d1c2d4
selection_background  #4e4352
active_border_color   #e7b4ff
inactive_border_color #4e4352
url_color             #e7b4ff

active_tab_foreground   #500075
active_tab_background   #e7b4ff
inactive_tab_foreground #d1c2d4
inactive_tab_background #4e4352
cursor_trail_color      #d1c2d4
