#!/usr/bin/env bash
# Runs after matugen writes ~/.config/nvim/lua/matugen.lua.
#
#  1. make sure something calls require('matugen').setup() at startup
#  2. on lazy.nvim, give bufferline.nvim a `highlights` function so its
#     per-filetype tab icon backgrounds can never drift from the tab colour
#     (see the note at the top of matugen-template.lua for why this lives
#     here instead of being patched reactively from inside the colorscheme)
#  3. signal any running Neovim to repaint (the module installs a SIGUSR1
#     handler)
#
# matugen.lua is a self-contained colorscheme - no plugins required. If your
# Neovim config doesn't source ~/.config/nvim/ (nvf, a flake, an isolated
# NVIM_APPNAME, ...) do step 1 yourself; see README.md.

set -euo pipefail

nvim_dir="${XDG_CONFIG_HOME:-$HOME/.config}/nvim"
lua_dir="$nvim_dir/lua"
init_lua="$nvim_dir/init.lua"
lazy_dir="${XDG_DATA_HOME:-$HOME/.local/share}/nvim/lazy/lazy.nvim"
plugin_spec="$lua_dir/plugins/matugen.lua"
bufferline_spec="$lua_dir/plugins/matugen-bufferline.lua"

loader="require('matugen').setup()"

if grep -rqsF "require('matugen')" "$lua_dir" "$init_lua" 2>/dev/null; then
  : # already wired up
elif [ -d "$lazy_dir" ]; then
  mkdir -p "$(dirname "$plugin_spec")"
  cat > "$plugin_spec" <<EOF
return {
  dir = vim.fn.stdpath('config'),
  name = 'matugen',
  lazy = false,
  priority = 1000,
  config = function()
    $loader
  end,
}
EOF
elif [ -f "$init_lua" ]; then
  printf '\n%s\n' "$loader" >> "$init_lua"
else
  echo "matugen: add \"$loader\" to your Neovim config (see README.md)" >&2
fi

if [ -d "$lazy_dir" ]; then
  mkdir -p "$(dirname "$bufferline_spec")"
  # This file's content never actually changes between reapplies (it reads
  # the palette live via require('matugen').get_palette() instead of baking
  # in colours), so only touch it if it's missing or its content differs --
  # writing it unconditionally on every wallpaper change touches its mtime
  # every time, which trips lazy.nvim's change-detection watcher and pops up
  # a "Config Change Detected" notice on every colour change for nothing.
  bufferline_spec_tmp="$(mktemp)"
  cat > "$bufferline_spec_tmp" <<'EOF'
-- Generated by matugen (neovim-base16 catalog entry). Do not edit by hand --
-- extends whatever bufferline.nvim spec you already have (or is a silent
-- no-op if you don't use bufferline) with a `highlights` function, so its
-- per-filetype tab icon backgrounds always match the tab they're drawn on.
-- bufferline calls this function fresh every time it re-derives its colours
-- (including on our own ColorScheme event), so it never goes stale.
return {
  'akinsho/bufferline.nvim',
  optional = true,
  opts = function(_, opts)
    opts.highlights = function(defaults)
      local ok, matugen = pcall(require, 'matugen')
      if not ok then
        return {}
      end
      local p = matugen.get_palette()
      -- Every state-based group (text, icons, diagnostics, numbers, modified
      -- dot, close button, ...) gets the same background as its tab, so a
      -- warning/error counter never punches a differently-coloured hole in
      -- the tab. Only bg is set; bufferline keeps deriving fg / sp itself.
      local families = {
        'buffer', 'numbers', 'close_button', 'modified',
        'duplicate', 'pick', 'separator', 'diagnostic',
        'hint', 'hint_diagnostic', 'info', 'info_diagnostic',
        'warning', 'warning_diagnostic', 'error', 'error_diagnostic',
      }
      local hl = {
        fill = { bg = p.nc },
        background = { bg = p.tab_bg },
        tab = { bg = p.tab_bg },
        tab_close = { bg = p.nc },
      }
      for _, name in ipairs(families) do
        hl[name] = { bg = p.tab_bg }
        hl[name .. '_visible'] = { bg = p.tab_bg }
        hl[name .. '_selected'] = { bg = p.tab_sel }
      end
      hl.buffer_selected.bold = true
      hl.buffer_selected.italic = false
      -- separators blend into the fill; the selected indicator stays accented
      for _, sfx in ipairs({ '', '_visible', '_selected' }) do
        hl['separator' .. sfx].fg = p.nc
      end
      hl.indicator_visible = { fg = p.tab_bg, bg = p.tab_bg }
      hl.indicator_selected = { fg = p.blue, bg = p.tab_sel }
      return hl
    end
  end,
}
EOF
  if ! cmp -s "$bufferline_spec_tmp" "$bufferline_spec" 2>/dev/null; then
    mv "$bufferline_spec_tmp" "$bufferline_spec"
  else
    rm -f "$bufferline_spec_tmp"
  fi
fi

pkill -SIGUSR1 nvim >/dev/null 2>&1 || true
