color0 #5a413c
color1 #ffb4ab
color2 #ffb4a6
color3 #ffb4a6
color4 #f3be5a
color5 #ffb4a6
color6 #ffb4a6
color7 #f8ddd7
color8 #a98983
color9 #ffb4ab
color10 #ffb4a6
color11 #ffb4a6
color12 #f3be5a
color13 #ffb4a6
color14 #ffb4a6
color15 #f8ddd7

cursor                #f8ddd7
cursor_text_color     #1d100d
background            #1d100d
foreground            #f8ddd7
selection_foreground  #e2beb8
selection_background  #5a413c
active_border_color   #ffb4a6
inactive_border_color #5a413c
url_color             #ffb4a6

active_tab_foreground   #650900
active_tab_background   #ffb4a6
inactive_tab_foreground #e2beb8
inactive_tab_background #5a413c
cursor_trail_color      #e2beb8
