color0 #f7dbe9
color1 #ba1a1a
color2 #aa1a8d
color3 #8d4577
color4 #ac341e
color5 #a55a8c
color6 #a55a8c
color7 #23181f
color8 #87717d
color9 #ba1a1a
color10 #aa1a8d
color11 #8d4577
color12 #ac341e
color13 #a55a8c
color14 #a55a8c
color15 #23181f

cursor                #23181f
cursor_text_color     #fff8f9
background            #fff8f9
foreground            #23181f
selection_foreground  #55414c
selection_background  #f7dbe9
active_border_color   #aa1a8d
inactive_border_color #f7dbe9
url_color             #aa1a8d

active_tab_foreground   #ffffff
active_tab_background   #aa1a8d
inactive_tab_foreground #55414c
inactive_tab_background #f7dbe9
cursor_trail_color      #55414c
