color0 #46464e
color1 #ffb4ab
color2 #bec3f5
color3 #c4c5db
color4 #ecb6dd
color5 #bec3f5
color6 #c4c5db
color7 #e4e1e6
color8 #919099
color9 #ffb4ab
color10 #bec3f5
color11 #c4c5db
color12 #ecb6dd
color13 #bec3f5
color14 #c4c5db
color15 #e4e1e6

cursor                #e4e1e6
cursor_text_color     #131316
background            #131316
foreground            #e4e1e6
selection_foreground  #c7c5cf
selection_background  #46464e
active_border_color   #bec3f5
inactive_border_color #46464e
url_color             #bec3f5

active_tab_foreground   #282d56
active_tab_background   #bec3f5
inactive_tab_foreground #c7c5cf
inactive_tab_background #46464e
cursor_trail_color      #c7c5cf
