color0 #504539
color1 #ffb4ab
color2 #f7bb70
color3 #dfc2a2
color4 #bbcd9e
color5 #f7bb70
color6 #dfc2a2
color7 #eee0d4
color8 #9c8e80
color9 #ffb4ab
color10 #f7bb70
color11 #dfc2a2
color12 #bbcd9e
color13 #f7bb70
color14 #dfc2a2
color15 #eee0d4

cursor                #eee0d4
cursor_text_color     #18120c
background            #18120c
foreground            #eee0d4
selection_foreground  #d4c4b5
selection_background  #504539
active_border_color   #f7bb70
inactive_border_color #504539
url_color             #f7bb70

active_tab_foreground   #472a00
active_tab_background   #f7bb70
inactive_tab_foreground #d4c4b5
inactive_tab_background #504539
cursor_trail_color      #d4c4b5
