color0 #151515
color1 #b66467
color2 #8c977d
color3 #d9bc8c
color4 #8da3b9
color5 #a988b0
color6 #8aa6a2
color7 #e0e0e0
color8 #414141
color9 #b66467
color10 #8c977d
color11 #d9bc8c
color12 #8da3b9
color13 #a988b0
color14 #8aa6a2
color15 #e8e3e3

cursor                #e0e0e0
cursor_text_color     #151515
background            #151515
foreground            #e0e0e0
selection_foreground  #e0e0e0
selection_background  #222222
active_border_color   #8da3b9
inactive_border_color #222222
url_color             #8da3b9

active_tab_foreground   #151515
active_tab_background   #8da3b9
inactive_tab_foreground #b0b0b0
inactive_tab_background #222222
cursor_trail_color      #b0b0b0
