-- Generated by matugen (neovim-base16 catalog entry). Do not edit by hand --
-- extends whatever bufferline.nvim spec you already have (or is a silent
-- no-op if you don't use bufferline) with a `highlights` function, so its
-- per-filetype tab icon backgrounds always match the tab they're drawn on.
-- bufferline calls this function fresh every time it re-derives its colours
-- (including on our own ColorScheme event), so it never goes stale.
return {
  'akinsho/bufferline.nvim',
  optional = true,
  opts = function(_, opts)
    opts.highlights = function(defaults)
      local ok, matugen = pcall(require, 'matugen')
      if not ok then
        return {}
      end
      local p = matugen.get_palette()
      -- Every state-based group (text, icons, diagnostics, numbers, modified
      -- dot, close button, ...) gets the same background as its tab, so a
      -- warning/error counter never punches a differently-coloured hole in
      -- the tab. Only bg is set; bufferline keeps deriving fg / sp itself.
      local families = {
        'buffer', 'numbers', 'close_button', 'modified',
        'duplicate', 'pick', 'separator', 'diagnostic',
        'hint', 'hint_diagnostic', 'info', 'info_diagnostic',
        'warning', 'warning_diagnostic', 'error', 'error_diagnostic',
      }
      local hl = {
        fill = { bg = p.nc },
        background = { bg = p.tab_bg },
        tab = { bg = p.tab_bg },
        tab_close = { bg = p.nc },
      }
      for _, name in ipairs(families) do
        hl[name] = { bg = p.tab_bg }
        hl[name .. '_visible'] = { bg = p.tab_bg }
        hl[name .. '_selected'] = { bg = p.tab_sel }
      end
      hl.buffer_selected.bold = true
      hl.buffer_selected.italic = false
      -- separators blend into the fill; the selected indicator stays accented
      for _, sfx in ipairs({ '', '_visible', '_selected' }) do
        hl['separator' .. sfx].fg = p.nc
      end
      hl.indicator_visible = { fg = p.tab_bg, bg = p.tab_bg }
      hl.indicator_selected = { fg = p.blue, bg = p.tab_sel }
      return hl
    end
  end,
}
