-- Generated by matugen (neovim-base16 catalog entry). Do not edit by hand --
-- extends whatever bufferline.nvim spec you already have (or is a silent
-- no-op if you don't use bufferline) with a `highlights` function, so its
-- per-filetype tab icon backgrounds always match the tab they're drawn on.
-- bufferline calls this function fresh every time it re-derives its colours
-- (including on our own ColorScheme event), so it never goes stale.
return {
  'akinsho/bufferline.nvim',
  optional = true,
  opts = function(_, opts)
    opts.highlights = function(defaults)
      local ok, matugen = pcall(require, 'matugen')
      if not ok then
        return {}
      end
      local p = matugen.get_palette()
      return {
        fill = { bg = p.nc },
        background = { bg = p.tab_bg },
        buffer_visible = { bg = p.tab_bg },
        buffer_selected = { bg = p.tab_sel, bold = true, italic = false },
      }
    end
  end,
}
